[tool.ruff]
line-length = 88
target-version = "py310"
fix = true
exclude = [
    "**/*.ipynb",  # Ignore all Jupyter notebooks
    "**/*.csv",     # Ignore all CSV files
]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.ruff.format]
quote-style = "single"